const fs = require('fs');
const path = require('path');
const { resolveChangeDir } = require('../../utils/change-utils');
const { walkFiles } = require('../../utils/file-walker');
const { parseBddScenarios } = require('../../utils/bdd-scenario-parser');

class PipelineCommand {
  constructor(cwd = process.cwd()) { this.cwd = cwd; }

  execute(changeName, options = {}) {
    const changeDir = changeName ? resolveChangeDir(path.join(this.cwd, 'stdd'), changeName) : null;
    const specsDir = changeName ? path.join(changeDir || '', 'specs') : path.join(this.cwd, 'stdd', 'specs');
    if (!fs.existsSync(specsDir)) throw new Error(`Spec directory not found: ${path.relative(this.cwd, specsDir)}`);
    const ir = this.parseSpecs(walkFiles(specsDir, { extensions: ['.feature', '.md'], skipDirs: new Set() }), this.cwd);
    const outDir = changeName ? path.join(changeDir, 'pipeline') : path.join(this.cwd, 'stdd', 'pipeline');
    fs.mkdirSync(outDir, { recursive: true });
    const irPath = path.join(outDir, 'ir.json');
    const testPath = path.join(outDir, 'generated-tests.test.js');
    fs.writeFileSync(irPath, JSON.stringify(ir, null, 2), 'utf8');
    fs.writeFileSync(testPath, this.generateTestSkeleton(ir), 'utf8');
    if (options.json) console.log(JSON.stringify({ status: 'generated', ir: irPath, tests: testPath }, null, 2));
    else console.log(`Generated pipeline IR and test skeleton in ${path.relative(this.cwd, outDir)}`);
    return { status: 'generated', ir: irPath, tests: testPath };
  }

  parseSpecs(files, cwd) {
    const scenarios = parseBddScenarios(files, cwd);
    return { version: '1.0', generatedAt: new Date().toISOString(), scenarios };
  }

  generateTestSkeleton(ir) {
    const lines = ['// Auto-generated by stdd pipeline', "const assert = require('assert');", ''];
    for (const scenario of ir.scenarios) {
      lines.push(`test(${JSON.stringify(scenario.name)}, () => {`);
      lines.push(`  // Source: ${scenario.source}`);
      for (const step of scenario.steps) lines.push(`  // ${step}`);
      lines.push("  assert.ok(false, 'Implement acceptance test from generated IR');");
      lines.push('});', '');
    }
    return lines.join('\n');
  }
}

module.exports = { PipelineCommand };
