const fs = require('fs');
const path = require('path');
const os = require('os');
const { MemoryScanner } = require('../src/cli/commands/memory-scan');

describe('MemoryScanner', () => {
  let tempDirs = [];

  function createTempDir(prefix = 'stdd-memory-test-') {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
    tempDirs.push(dir);
    return dir;
  }

  function createProjectStructure(baseDir, files) {
    for (const [relPath, content] of Object.entries(files)) {
      const fullPath = path.join(baseDir, relPath);
      const dir = path.dirname(fullPath);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(fullPath, content, 'utf-8');
    }
  }

  afterAll(() => {
    for (const dir of tempDirs) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  describe('scan', () => {
    it('should generate components.md with tree structure for multi-level src', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/index.js': 'export const app = {};',
        'src/components/Button.js': 'export function Button() {}',
        'src/components/Input.js': 'export function Input() {}',
        'src/components/Modal.js': 'export function Modal() {}',
        'src/components/forms/FormInput.js': 'export function FormInput() {}',
        'src/utils/format.js': 'export function formatDate() {}',
        'src/utils/validate.js': 'export function validateEmail() {}',
        'src/services/api.js': 'export class ApiService {}',
        'src/services/auth.js': 'export function login() {}',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      expect(result.fileCount).toBe(9);
      expect(fs.existsSync(result.componentsPath)).toBe(true);

      const componentsContent = fs.readFileSync(result.componentsPath, 'utf-8');
      expect(componentsContent).toContain('Auto-generated by `stdd memory scan`');
      expect(componentsContent).toContain('src/components/Button.js');
      expect(componentsContent).toContain('src/utils/format.js');
      expect(componentsContent).toContain('src/services/api.js');
      expect(componentsContent).toContain('├──');
      expect(componentsContent).toContain('└──');
    });

    it('should generate contracts.md with exported symbols', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/index.js': `
export function main() { return 'main'; }
export class App {}
export const VERSION = '1.0.0';
`,
        'src/components/Button.js': `
export function Button({ label }) { return label; }
export const DefaultButton = () => 'button';
`,
        'src/services/api.js': `
export class ApiService {
  constructor(config) {}
  async fetch(url) {}
}
export async function fetchData(url) { return url; }
`,
        'src/utils/helpers.js': `
export function formatDate(date) {}
export const formatNumber = (n) => n.toString();
`,
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      expect(fs.existsSync(result.contractsPath)).toBe(true);

      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');
      expect(contractsContent).toContain('Auto-generated by `stdd memory scan`');
      expect(contractsContent).toContain('API Surface');

      expect(contractsContent).toContain('main');
      expect(contractsContent).toContain('Button');
      expect(contractsContent).toContain('ApiService');
      expect(contractsContent).toContain('fetchData');
      expect(contractsContent).toContain('formatDate');
      expect(contractsContent).toContain('VERSION');
    });

    it('should handle TypeScript files with interfaces and types', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/types.ts': `
export interface User {
  id: string;
  name: string;
}
export type UserRole = 'admin' | 'user';
`,
        'src/index.ts': `
export function getUser(id: string): User {
  return { id, name: '' };
}
`,
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');
      expect(contractsContent).toContain('User');
      expect(contractsContent).toContain('UserRole');
      expect(contractsContent).toContain('getUser');
    });

    it('should handle Python files', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/models.py': `
class User:
    def __init__(self, name):
        self.name = name
`,
        'src/services.py': `
def get_user(user_id):
    pass

def create_user(name):
    pass
`,
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();
      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');

      expect(contractsContent).toContain('User');
      expect(contractsContent).toContain('get_user');
      expect(contractsContent).toContain('create_user');
    });

    it('should handle module.exports pattern', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/utils.js': `
module.exports = {
  format,
  validate,
  parse
};
`,
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');
      expect(contractsContent).toContain('format');
      expect(contractsContent).toContain('validate');
      expect(contractsContent).toContain('parse');
    });

    it('should honor custom sourceDir option', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'lib/main.js': 'export function main() {}',
        'lib/helpers.js': 'export function helper() {}',
        'src/ignored.js': 'export function ignored() {}',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan({ sourceDir: path.join(baseDir, 'lib') });

      expect(result.fileCount).toBe(2);
      const componentsContent = fs.readFileSync(result.componentsPath, 'utf-8');
      expect(componentsContent).toContain('main.js');
      expect(componentsContent).toContain('helpers.js');
      expect(componentsContent).not.toContain('ignored.js');
    });

    it('should handle empty source directory', async () => {
      const baseDir = createTempDir();
      fs.mkdirSync(path.join(baseDir, 'src'), { recursive: true });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      expect(result.fileCount).toBe(0);

      const componentsContent = fs.readFileSync(result.componentsPath, 'utf-8');
      expect(componentsContent).toContain('no source files found');
    });

    it('should read source_root from config.yaml', async () => {
      const baseDir = createTempDir();
      fs.mkdirSync(path.join(baseDir, 'stdd'), { recursive: true });
      fs.writeFileSync(
        path.join(baseDir, 'stdd', 'config.yaml'),
        'source_root: "custom/src"\n',
        'utf-8'
      );

      createProjectStructure(baseDir, {
        'custom/src/app.js': 'export function app() {}',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      expect(result.fileCount).toBe(1);
    });
  });

  describe('listMemory', () => {
    it('should list memory files with metadata', async () => {
      const baseDir = createTempDir();
      const memoryDir = path.join(baseDir, 'stdd', 'memory');
      fs.mkdirSync(memoryDir, { recursive: true });
      fs.writeFileSync(path.join(memoryDir, 'components.md'), '# Components', 'utf-8');
      fs.writeFileSync(path.join(memoryDir, 'contracts.md'), '# Contracts', 'utf-8');
      fs.writeFileSync(path.join(memoryDir, 'foundation.md'), '# Foundation', 'utf-8');

      const scanner = new MemoryScanner(baseDir);
      const files = await scanner.listMemory();

      expect(files).toHaveLength(3);
      expect(files[0]).toHaveProperty('name');
      expect(files[0]).toHaveProperty('size');
      expect(files[0]).toHaveProperty('modified');
      expect(files[0].name).toMatch(/\.md$/);
    });

    it('should return empty array when memory dir does not exist', async () => {
      const baseDir = createTempDir();

      const scanner = new MemoryScanner(baseDir);
      const files = await scanner.listMemory();

      expect(files).toEqual([]);
    });
  });

  describe('buildFileTree', () => {
    it('should create correct tree structure', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/a.js': '',
        'src/b/c.js': '',
        'src/b/d.js': '',
        'src/e/f/g.js': '',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      const componentsContent = fs.readFileSync(result.componentsPath, 'utf-8');
      expect(componentsContent).toContain('src/');
      expect(componentsContent).toContain('a.js');
      expect(componentsContent).toContain('b/');
      expect(componentsContent).toContain('c.js');
      expect(componentsContent).toContain('d.js');
      expect(componentsContent).toContain('e/');
      expect(componentsContent).toContain('f/');
      expect(componentsContent).toContain('g.js');
    });
  });

  describe('inferPurpose', () => {
    let scanner;

    beforeEach(() => {
      scanner = new MemoryScanner();
    });

    it('should infer component purposes', () => {
      expect(scanner.inferPurpose('Button.js', 'src/components')).toContain('Button');
      expect(scanner.inferPurpose('Input.js', 'src/components')).toContain('Input');
      expect(scanner.inferPurpose('Modal.js', 'src/components')).toContain('Modal');
    });

    it('should infer utility purposes', () => {
      expect(scanner.inferPurpose('format.js', 'src/utils')).toContain('Formatting');
      expect(scanner.inferPurpose('date.js', 'src/utils')).toContain('Date');
      expect(scanner.inferPurpose('validate.js', 'src/utils')).toContain('Validation');
    });

    it('should infer service purposes', () => {
      expect(scanner.inferPurpose('auth.js', 'src/services')).toContain('Authentication');
      expect(scanner.inferPurpose('api.js', 'src/services')).toContain('API');
    });

    it('should infer index file purpose', () => {
      expect(scanner.inferPurpose('index.js', 'src')).toContain('entry');
    });
  });
});
