const fs = require('fs');
const path = require('path');
const os = require('os');
const { MemoryScanner } = require('../src/cli/commands/memory-scan');

describe('MemoryScanner', () => {
  let tempDirs = [];

  function createTempDir(prefix = 'stdd-memory-test-') {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
    tempDirs.push(dir);
    return dir;
  }

  function createProjectStructure(baseDir, files) {
    for (const [relPath, content] of Object.entries(files)) {
      const fullPath = path.join(baseDir, relPath);
      const dir = path.dirname(fullPath);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(fullPath, content, 'utf-8');
    }
  }

  afterAll(() => {
    for (const dir of tempDirs) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  describe('scan', () => {
    it('should generate components.md with tree structure for multi-level src', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/index.js': 'export const app = {};',
        'src/components/Button.js': 'export function Button() {}',
        'src/components/Input.js': 'export function Input() {}',
        'src/components/Modal.js': 'export function Modal() {}',
        'src/components/forms/FormInput.js': 'export function FormInput() {}',
        'src/utils/format.js': 'export function formatDate() {}',
        'src/utils/validate.js': 'export function validateEmail() {}',
        'src/services/api.js': 'export class ApiService {}',
        'src/services/auth.js': 'export function login() {}',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      expect(result.fileCount).toBe(9);
      expect(fs.existsSync(result.componentsPath)).toBe(true);

      const componentsContent = fs.readFileSync(result.componentsPath, 'utf-8');
      expect(componentsContent).toContain('Auto-generated by `stdd memory scan`');
      expect(componentsContent).toContain('src/components/Button.js');
      expect(componentsContent).toContain('src/utils/format.js');
      expect(componentsContent).toContain('src/services/api.js');
      expect(componentsContent).toContain('├──');
      expect(componentsContent).toContain('└──');
    });

    it('should generate contracts.md with exported symbols', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/index.js': `
export function main() { return 'main'; }
export class App {}
export const VERSION = '1.0.0';
`,
        'src/components/Button.js': `
export function Button({ label }) { return label; }
export const DefaultButton = () => 'button';
`,
        'src/services/api.js': `
export class ApiService {
  constructor(config) {}
  async fetch(url) {}
}
export async function fetchData(url) { return url; }
`,
        'src/utils/helpers.js': `
export function formatDate(date) {}
export const formatNumber = (n) => n.toString();
`,
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      expect(fs.existsSync(result.contractsPath)).toBe(true);

      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');
      expect(contractsContent).toContain('Auto-generated by `stdd memory scan`');
      expect(contractsContent).toContain('API Surface');

      expect(contractsContent).toContain('main');
      expect(contractsContent).toContain('Button');
      expect(contractsContent).toContain('ApiService');
      expect(contractsContent).toContain('fetchData');
      expect(contractsContent).toContain('formatDate');
      expect(contractsContent).toContain('VERSION');
    });

    it('should handle TypeScript files with interfaces and types', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/types.ts': `
export interface User {
  id: string;
  name: string;
}
export type UserRole = 'admin' | 'user';
`,
        'src/index.ts': `
export function getUser(id: string): User {
  return { id, name: '' };
}
`,
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');
      expect(contractsContent).toContain('User');
      expect(contractsContent).toContain('UserRole');
      expect(contractsContent).toContain('getUser');
    });

    it('should handle Python files', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/models.py': `
class User:
    def __init__(self, name):
        self.name = name
`,
        'src/services.py': `
def get_user(user_id):
    pass

def create_user(name):
    pass
`,
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();
      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');

      expect(contractsContent).toContain('User');
      expect(contractsContent).toContain('get_user');
      expect(contractsContent).toContain('create_user');
    });

    it('should handle module.exports pattern', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/utils.js': `
module.exports = {
  format,
  validate,
  parse
};
`,
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');
      expect(contractsContent).toContain('format');
      expect(contractsContent).toContain('validate');
      expect(contractsContent).toContain('parse');
    });

    it('should honor custom sourceDir option', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'lib/main.js': 'export function main() {}',
        'lib/helpers.js': 'export function helper() {}',
        'src/ignored.js': 'export function ignored() {}',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan({ sourceDir: path.join(baseDir, 'lib') });

      expect(result.fileCount).toBe(2);
      const componentsContent = fs.readFileSync(result.componentsPath, 'utf-8');
      expect(componentsContent).toContain('main.js');
      expect(componentsContent).toContain('helpers.js');
      expect(componentsContent).not.toContain('ignored.js');
    });

    it('should handle empty source directory', async () => {
      const baseDir = createTempDir();
      fs.mkdirSync(path.join(baseDir, 'src'), { recursive: true });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      expect(result.fileCount).toBe(0);

      const componentsContent = fs.readFileSync(result.componentsPath, 'utf-8');
      expect(componentsContent).toContain('no source files found');
    });

    it('should produce no symbols message when files have no exports', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/plain.js': 'const x = 1;\n// no exports',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');
      expect(contractsContent).toContain('No exported symbols found');
    });

    it('should handle exports.name = pattern', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/legacy.js': 'exports.myFunc = function() {};\nexports.myVal = 42;',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');
      expect(contractsContent).toContain('myFunc');
      expect(contractsContent).toContain('myVal');
    });

    it('should handle Python class with inheritance', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/models.py': 'class Admin(User):\n    pass\n',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');
      expect(contractsContent).toContain('Admin');
      expect(contractsContent).toContain('(User)');
    });

    it('should handle Python class without inheritance', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/models.py': 'class Standalone:\n    pass\n',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      const contractsContent = fs.readFileSync(result.contractsPath, 'utf-8');
      expect(contractsContent).toContain('Standalone');
    });

    it('should skip dot-directories and node_modules in findSourceFiles', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/.hidden/file.js': 'export const a = 1;',
        'src/node_modules/pkg/index.js': 'export const b = 2;',
        'src/visible/file.js': 'export const c = 3;',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      expect(result.fileCount).toBe(1);
    });

    it('should handle config.yaml with null source_root', async () => {
      const baseDir = createTempDir();
      fs.mkdirSync(path.join(baseDir, 'stdd'), { recursive: true });
      fs.writeFileSync(
        path.join(baseDir, 'stdd', 'config.yaml'),
        'source_root: null\n',
        'utf-8'
      );

      createProjectStructure(baseDir, {
        'src/app.js': 'export function app() {}',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      // Falls back to default src/ directory
      expect(result.fileCount).toBe(1);
    });

    it('should read source_root from config.yaml', async () => {
      const baseDir = createTempDir();
      fs.mkdirSync(path.join(baseDir, 'stdd'), { recursive: true });
      fs.writeFileSync(
        path.join(baseDir, 'stdd', 'config.yaml'),
        'source_root: "custom/src"\n',
        'utf-8'
      );

      createProjectStructure(baseDir, {
        'custom/src/app.js': 'export function app() {}',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      expect(result.fileCount).toBe(1);
    });
  });

  describe('listMemory', () => {
    it('should list memory files with metadata', async () => {
      const baseDir = createTempDir();
      const memoryDir = path.join(baseDir, 'stdd', 'memory');
      fs.mkdirSync(memoryDir, { recursive: true });
      fs.writeFileSync(path.join(memoryDir, 'components.md'), '# Components', 'utf-8');
      fs.writeFileSync(path.join(memoryDir, 'contracts.md'), '# Contracts', 'utf-8');
      fs.writeFileSync(path.join(memoryDir, 'foundation.md'), '# Foundation', 'utf-8');

      const scanner = new MemoryScanner(baseDir);
      const files = await scanner.listMemory();

      expect(files).toHaveLength(3);
      expect(files[0]).toHaveProperty('name');
      expect(files[0]).toHaveProperty('size');
      expect(files[0]).toHaveProperty('modified');
      expect(files[0].name).toMatch(/\.md$/);
    });

    it('should return empty array when memory dir does not exist', async () => {
      const baseDir = createTempDir();

      const scanner = new MemoryScanner(baseDir);
      const files = await scanner.listMemory();

      expect(files).toEqual([]);
    });

    it('should throw non-ENOENT errors from listMemory', async () => {
      const baseDir = createTempDir();
      const memoryDir = path.join(baseDir, 'stdd', 'memory');
      fs.mkdirSync(memoryDir, { recursive: true });
      // Make the directory unreadable (no read permission)
      fs.chmodSync(memoryDir, 0o000);

      const scanner = new MemoryScanner(baseDir);
      await expect(scanner.listMemory()).rejects.toThrow();

      // Restore permissions for cleanup
      fs.chmodSync(memoryDir, 0o755);
    });
  });

  describe('buildFileTree', () => {
    it('should create correct tree structure', async () => {
      const baseDir = createTempDir();

      createProjectStructure(baseDir, {
        'src/a.js': '',
        'src/b/c.js': '',
        'src/b/d.js': '',
        'src/e/f/g.js': '',
      });

      const scanner = new MemoryScanner(baseDir);
      const result = await scanner.scan();

      const componentsContent = fs.readFileSync(result.componentsPath, 'utf-8');
      expect(componentsContent).toContain('src/');
      expect(componentsContent).toContain('a.js');
      expect(componentsContent).toContain('b/');
      expect(componentsContent).toContain('c.js');
      expect(componentsContent).toContain('d.js');
      expect(componentsContent).toContain('e/');
      expect(componentsContent).toContain('f/');
      expect(componentsContent).toContain('g.js');
    });
  });

  describe('inferPurpose', () => {
    let scanner;

    beforeEach(() => {
      scanner = new MemoryScanner();
    });

    it('should infer component purposes', () => {
      expect(scanner.inferPurpose('Button.js', 'src/components')).toContain('Button');
      expect(scanner.inferPurpose('Input.js', 'src/components')).toContain('Input');
      expect(scanner.inferPurpose('Modal.js', 'src/components')).toContain('Modal');
    });

    it('should infer utility purposes', () => {
      expect(scanner.inferPurpose('format.js', 'src/utils')).toContain('Formatting');
      expect(scanner.inferPurpose('date.js', 'src/utils')).toContain('Date');
      expect(scanner.inferPurpose('validate.js', 'src/utils')).toContain('Validation');
    });

    it('should infer service purposes', () => {
      expect(scanner.inferPurpose('auth.js', 'src/services')).toContain('Authentication');
      expect(scanner.inferPurpose('api.js', 'src/services')).toContain('API');
    });

    it('should infer index file purpose', () => {
      expect(scanner.inferPurpose('index.js', 'src')).toContain('entry');
    });

    it('should infer header, footer, form, list, table, card, nav component purposes', () => {
      expect(scanner.inferPurpose('Header.js', 'src/components')).toContain('Header');
      expect(scanner.inferPurpose('Footer.js', 'src/components')).toContain('Footer');
      expect(scanner.inferPurpose('SearchForm.js', 'src/components')).toContain('Form');
      expect(scanner.inferPurpose('UserList.js', 'src/components')).toContain('List');
      expect(scanner.inferPurpose('DataTable.js', 'src/components')).toContain('Table');
      expect(scanner.inferPurpose('ProfileCard.js', 'src/components')).toContain('Card');
      expect(scanner.inferPurpose('TopNav.js', 'src/components')).toContain('Navigation');
    });

    it('should return generic UI Component for unmatched component files', () => {
      expect(scanner.inferPurpose('Widget.js', 'src/components')).toBe('UI Component');
    });

    it('should infer string, array, math utility purposes', () => {
      expect(scanner.inferPurpose('string.js', 'src/utils')).toContain('String');
      expect(scanner.inferPurpose('array.js', 'src/helpers')).toContain('Array');
      expect(scanner.inferPurpose('math.js', 'src/utils')).toContain('Math');
    });

    it('should return generic utility for unmatched util files', () => {
      expect(scanner.inferPurpose('crypto.js', 'src/utils')).toBe('Utility functions');
    });

    it('should infer data service purpose', () => {
      expect(scanner.inferPurpose('data.js', 'src/services')).toContain('Data');
    });

    it('should return generic service for unmatched service files', () => {
      expect(scanner.inferPurpose('payment.js', 'src/services')).toBe('Business logic service');
    });

    it('should infer model, controller, route, config, test, middleware, hook purposes', () => {
      expect(scanner.inferPurpose('user.js', 'src/models')).toBe('Data model definition');
      expect(scanner.inferPurpose('user.js', 'src/entity')).toBe('Data model definition');
      expect(scanner.inferPurpose('app.js', 'src/controllers')).toBe('Request handler controller');
      expect(scanner.inferPurpose('routes.js', 'src/routes')).toBe('Route definitions');
      expect(scanner.inferPurpose('routes.js', 'src/router')).toBe('Route definitions');
      expect(scanner.inferPurpose('settings.js', 'src/config')).toBe('Configuration module');
      expect(scanner.inferPurpose('settings.js', 'src/conf')).toBe('Configuration module');
      expect(scanner.inferPurpose('app.test.js', 'src/test')).toBe('Test suite');
      expect(scanner.inferPurpose('app.spec.js', 'src/spec')).toBe('Test suite');
      expect(scanner.inferPurpose('auth.js', 'src/middleware')).toBe('Request middleware');
      expect(scanner.inferPurpose('useAuth.js', 'src/hook')).toBe('Custom hook');
    });

    it('should infer name-based purposes for app, main, config, constant, type, interface', () => {
      expect(scanner.inferPurpose('app.js', 'src')).toContain('Application');
      expect(scanner.inferPurpose('main.js', 'src')).toContain('Main');
      expect(scanner.inferPurpose('config.js', 'src')).toBe('Configuration');
      expect(scanner.inferPurpose('constant.js', 'src')).toBe('Constants definition');
      expect(scanner.inferPurpose('types.js', 'src')).toBe('Type definitions');
      expect(scanner.inferPurpose('interfaces.js', 'src')).toBe('Interface definitions');
    });

    it('should return generic Source module for unmatched files', () => {
      expect(scanner.inferPurpose('foobar.js', 'src')).toBe('Source module');
    });
  });
});
